[[redirects]]
  from = "/*"
  to = "/"
  status = 200

[build]
  functions = "netlify/functions"

[functions]
  directory = "netlify/functions/"
  external_node_modules = ["json-server"]

[[redirects]]
  from = "/netlify/functions/*"
  to = "/netlify/functions/:splat"
  status = 200